// Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
// or more contributor license agreements. Licensed under the Elastic License;
// you may not use this file except in compliance with the Elastic License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package meraki

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "meraki", asset.ModuleFieldsPri, AssetMeraki); err != nil {
		panic(err)
	}
}

// AssetMeraki returns asset data.
// This is the base64 encoded zlib format compressed contents of module/meraki.
func AssetMeraki() string {
	return "eJx8jjuugzAURHuvYkTPBly87q0juuAJsfBPtpHC7iNCQCG/KefcqzMtRs4anllGq4Bqq6NGsxaNAjIdpVCjYxUFGJY+21RtDBp/CsDjGz6ayfHeLGkRxFPDSLl0UbI5SbI7BeqcqDHkOKWn9lW35YN2R18EZ0tnij7cbqP6OIXKfGDbJBsqhzf2Y8CS/6v45LhK1S0AAP//kHBbgA=="
}
